import {
  toXmlDemographics,
  toXmlFamHistory,
  toXmlPastHealth,
  toXmlProblemList,
  toXmlRiskFactors,
  toXmlAllergies,
  toXmlMedications,
  toXmlImmunizations,
  toXmlLabResults,
  toXmlAppointments,
} from "./xmlTemplates";

export const recordCategories = [
  {
    id: 1,
    name: "Demographics",
    label: "Demographics",
    url: "/export/demographics",
    template: toXmlDemographics,
  },
  {
    id: 2,
    name: "FamilyHistory",
    label: "Family History",
    url: "/export/family_history",
    template: toXmlFamHistory,
  },
  {
    id: 3,
    name: "PastHealth",
    label: "Past Health",
    url: "/export/past_health",
    template: toXmlPastHealth,
  },
  {
    id: 4,
    name: "ProblemList",
    label: "Problem List",
    url: "/export/problem_list",
    template: toXmlProblemList,
  },
  {
    id: 5,
    name: "RiskFactors",
    label: "Risk Factors",
    url: "/export/risk_factors",
    template: toXmlRiskFactors,
  },
  {
    id: 6,
    name: "AllergiesAndAdverseReactions",
    label: "Allergies And Adverse Reactions",
    url: "/export/allergies",
    template: toXmlAllergies,
  },
  {
    id: 7,
    name: "MedicationsAndTreatments",
    label: "Medications And Treatments",
    url: "/export/medications",
    template: toXmlMedications,
  },
  {
    id: 8,
    name: "Immunizations",
    label: "Immunizations",
    url: "/export/immunizations",
    template: toXmlImmunizations,
  },
  {
    id: 9,
    name: "LaboratoryResults",
    label: "Laboratory Results",
    url: "/export/laboratory_results",
    template: toXmlLabResults,
  },
  {
    id: 10,
    name: "Appointments",
    label: "Appointments",
    url: "/export/appointments",
    template: toXmlAppointments,
  },
  {
    id: 11,
    name: "ClinicalNotes",
    label: "Clinical Notes",
    url: "/export/clinical_notes",
  },
  { id: 12, name: "Reports", label: "Reports", url: "/export/reports" },
  {
    id: 13,
    name: "CareElements",
    label: "Care Elements",
    url: "/export/care_elements",
  },
  {
    id: 14,
    name: "AlertsAndSpecialNeeds",
    label: "Alerts And Special Needs",
    url: "/export/alerts",
  },
];
